version: 0.2

phases:
  build:
    commands:
      - dotnet restore AWSLambdaTEST.sln
      - dotnet publish -c release -o ./build_output AWSLambdaTEST.sln
      - printenv
artifacts:
  files:
    - AWSLambdaTEST/build_output/**/*
  discard-paths: yes
